### ISSUE TITLE
Logger

### ISSUE THREAD

**Issue by psyomn** [space-concordia-robotics/robotics-networking#2]
Write a logger for the networking stuff. For this, it would be nice if we make it store the logs in common directories.

For linux, make it store the logs in: `$HOME/.config/roboticsnet/log.txt`

For Windows it should store it in: `%APPDATA%/roboticsnet/log.txt`

I think this is a good beginner task for anyone that wants to give a try at python.

You should be able to log the following under the categories:
* **Info**rmation
* **erro**r
* **warn**ing

```python
Log.i("I'm logging information")
Log.w("I'm logging a warning")
Log.e("I'm logging an error")
```

Which should return something like:

````
[DD/MM/YYYY HH:MM:SS] [INFO] I'm logging information
[DD/MM/YYYY HH:MM:SS] [WARN] I'm logging information
[DD/MM/YYYY HH:MM:SS] [ERRO] I'm logging information
````

**Comment by psyomn** [comment]
So what's happening with this?

**Comment by psyomn** [comment]
@Doomfest

**Comment by Doomfest** [comment]
Haven't started this yet. I am working on ucontr manager right now.

**Comment by psyomn** [comment]
I'm going to take this out of your hands, just for the sake of closing this milestone.

**Comment by Doomfest** [comment]
Is this done @psyomn ?

**Comment by psyomn** [comment]
No. This was your task.

**Comment by Doomfest** [comment]
kk

**Comment by psyomn** [comment]
@Doomfest

**Comment by psyomn** [comment]
@Doomfest Reminder: think of spawning this as a process or thread with a queue, where you can delegate things to log to a file. This way writes will not block the rest of the execution of the system.

You should also think about parametrizing the constructor of this component such that you can redirect logging to `stdout`, `stderr`, or even to `/dev/null`.

**Comment by psyomn** [comment]
Actually come to think of it, this feature is related to all three projects. We could definitely create a fourth repository, and make a generic logger (or reuse something existing but adapt it to our needs). 

Then we use that implementation across all three projects, including this one. 

@Doomfest @msnidal @arevans3 what do you think?

**Comment by psyomn** [comment]
This now has its own repository.

https://github.com/space-concordia-robotics/robotics-logger

Waiting for an implementation to implement logging through said library now.

**Comment by psyomn** [comment]
Bump.

**Comment by Doomfest** [comment]
Logger is done. You can start using it.
