### ISSUE TITLE
Need to check all the movements and the values they send.

### ISSUE THREAD

**Issue by Doomfest** [space-concordia-robotics/robotics-networking#29]
We need to take a look at all the values the client sends to server and if the server properly gets them and sends them to the micro manager properly. It seems like the forward, reverse, turn and sotp comamnds do nothing because hte c;lient sends valeus anyway.

**Comment by psyomn** [comment]
What do you mean? There's some validation stuff that needs some working on, and the server seems to be getting normal values. Do you mean from the rover-core to the actual arduino?

**Comment by psyomn** [comment]
@Doomfest bump

**Comment by psyomn** [comment]
@Doomfest

**Comment by Doomfest** [comment]
This is done.
