### ISSUE TITLE
Protocol needs to be updated.

### ISSUE THREAD

**Issue by Doomfest** [space-concordia-robotics/robotics-networking#3]
The protocol needs to be update to:
For data sent to arduino:
command + val2 + val1 + reserved.

Each part is a hex number. The whole packet will be 4 bytes.

command will be a hex table with all the commands for the rover.
val2 and val1 are values needed to be sent to the sensors + motors.
reserved is a revserved byte for extra options in the future.

For data sent from arduino back to the process:

[we need to figure  out which format will be coming back to process]

This is a good start might be changed a bit in the near future when we get more information on the sensors.

**Comment by psyomn** [comment]
I don't think there's anything else to add here. Source-code wise this is done. I need to recheck a few things but overall we can close this for now.
