### ISSUE TITLE
Client side human usability.

### ISSUE THREAD

**Issue by Doomfest** [space-concordia-robotics/robotics-networking#30]
I am thinking about the values on the client side being rate of change in degrees. Like the client can tell the rover to turn left at a rate of 20 degrees/s. It will make it easier for humans to use.

What do you think?

**Comment by psyomn** [comment]
Just add more commands in the form of:

--turnLeftDg <value>
--turnRightDg <value>
...

**Comment by Doomfest** [comment]
Mark and I changed the forward, reverse, turnLeft andturnRight commands as follows:

roboclientname <commandName> <speed (1-63)>

theres also a stop command which stops all motors
roboclientname stop

This isssue should be done, but we might need to add thigns in the future. I will close this for now.

**Comment by psyomn** [comment]
Don't forget to update the README
