### ISSUE TITLE
Close sockets on server shutdown (graceful)

### ISSUE THREAD

**Issue by msnidal** [space-concordia-robotics/robotics-networking#34]
If you try and restart the server after having already run it and shut it down via the --graceful command, it produces this error:

````
rover@rover-desktop ~/programming/robotics-rover/roboticsrov $ roboticsrov-test
Connected to port. /dev/ttyACM0
Waiting some time for microcontroller's serial to startup...
Robotics Rover   0.0.1
Starting command dispatcher...
Listening on port:  5000
Traceback (most recent call last):
  File "/home/rover/.local/bin/roboticsrov-test", line 10, in <module>
    execfile(__file__)
  File "/home/rover/programming/robotics-rover/roboticsrov/bin/roboticsrov-test", line 26, in <module>
    server.listen()
  File "/home/rover/programming/robotics-networking/roboticsnet/rover_listener.py", line 33, in listen
    l = Listener(address)
  File "/usr/lib/python2.7/multiprocessing/connection.py", line 132, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/usr/lib/python2.7/multiprocessing/connection.py", line 256, in __init__
    self._socket.bind(address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
````
https://gist.github.com/msnidal/9b32639bd42335c03e9e

Right now I'm not sure if this is a network or a rover problem, but it looks like the sockets aren't properly closed somewhere. We should identify the exact problem and fix this so we can restart the server if we need to.

**Comment by psyomn** [comment]
Graceful not so graceful it seems. Sorry about that. 

Check out `lsof` on linux to monitor for open sockets/files.

**Comment by psyomn** [comment]
I might take this off your hands today!

**Comment by psyomn** [comment]
So I'm trying to reproduce the error but I'm not seeing anything via graceful:

![screen](https://cloud.githubusercontent.com/assets/505688/10107708/f1596502-638a-11e5-8887-0237d2043725.png)

I also tried interrupting the program, and restarting but it seems it closes the previously opened port.

I did spot however a possible way to represent the listening look a little better. It's by adding a `finally` clause (so in case something happens in that loop - or does not, we have a guarantee that the port will be closed).

````python
        while not self.end_listen:
            try:
                conn = l.accept()
                received_bytes = conn.recv_bytes()

                print "Received: ",
                print(Fore.GREEN + RoverUtils.hexArrToHumanReadableString(received_bytes))
                print(Fore.RESET)

                if ord(received_bytes[0]) == ROBOTICSNET_COMMAND_GRACEFUL:
                    self.end_listen = True
                else:
                    cmd = CommandFactory.makeFromByteArray(\
                            received_bytes,
                            conn,
                            self.session,
                            self.hooks)
                    cmd.execute()

            except KeyboardInterrupt:
                print "Shutting down ..."
                self.end_listen = True

            except:
                # TODO: logging would be a good idea here
                print "There was some error. Ignoring last command"
                print traceback.format_exc()

            finally:
                conn.close()
````

**Comment by psyomn** [comment]
Oh crap! I just saw you're using `roboticsnet-test`. I don't remember when, but we changed that script to `roboticsnet-server`. I'm suspecting maybe there's some artifact left on the rover from a previous install, which might be using something older which might not have been as sane. I guess I'll have to check when I'm in lab, on the actual rover.

**Comment by psyomn** [comment]
And apparently I can't read. Perception check fail! This is on the rover, which borrows from the networking library. I'm suspecting the problem is the socket opened for the serial communication to the microcontroller - if it crashes, that is the one that is not closed. I can take a look at source later. Until we confirm, I'll leave this open, but from what I see here, I highly doubt it's the networking code.
