### ISSUE TITLE
Re-arrange the protocl values and add reserved slots.

### ISSUE THREAD

**Issue by Doomfest** [space-concordia-robotics/robotics-networking#36]
Need to Re-arrange the protcol values to something more organized and add reserved slots between different group actions so we dont to keep pushing everythign around.

**Comment by psyomn** [comment]
What exactly do you mean?

**Comment by arevans3** [comment]
I had to make reverseleft and reverseright 0x09 and 0x10, so now everything's a bit disorganized and if we need to add more commands it'll only get worse.

**Comment by Doomfest** [comment]
Ill fix this.

**Comment by psyomn** [comment]
Is this referring to anything in particular anymore? Was this resolved?

**Comment by Doomfest** [comment]
Rearranged the protocol values for future proofing. (needs to be tested in lab on minirover)

Also how do you fix this error?

======================================================================
ERROR: testAttrSet (test.test_client_validation.TestClientValidation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/space-concordia-robotics/robotics-networking/test/test_client_validation.py", line 30, in testAttrSet
    self.assertEqual(self.cm.getHost(), 'myhost')
  File "/home/travis/build/space-concordia-robotics/robotics-networking/roboticsnet/client/rover_client.py", line 22, in getHost
    def getHost(self): return self.host
AttributeError: ClientMock instance has no attribute 'host'

**Comment by Doomfest** [comment]
@simon @msnidal @arevans3

**Comment by msnidal** [comment]
The protocol values are generally in order now and the dictionary is up to date, so I'm closing this issue.
