### ISSUE TITLE
Investigate distributed timestamps

### ISSUE THREAD

**Issue by msnidal** [space-concordia-robotics/robotics-networking#37]
As a driver, I want to make sure that when the rover executes a move command that I've sent, the command was *very* recent. Furthermore, the rover motors should stop if there hasn't been a command recently.

The best way to achieve both of these in a reasonable way is with timestamps integrated into the networking code. We should look into distributed timestamps/lamport timestamps and then add them to robotics-networking commands.

**Comment by Doomfest** [comment]
related to #35

**Comment by psyomn** [comment]
I think what Arielle was saying was fine. We don't need anything too crazy. What we **do** need is something which can share the server and client time, where we can get a delta, so if there's any difference between the two clocks, we can get said difference. Then our timestamps will be relative.

**Comment by Doomfest** [comment]
Also check out state diagram.

**Comment by msnidal** [comment]
We're going to use UNIX timestamps with diff like @arevans3 suggested, for the reasons @psyomn mentioned and since Lamport timestamps are just an ordering (which is interesting but probably not very practical for our needs.)
