### ISSUE TITLE
Protocol review

### ISSUE THREAD

**Issue by msnidal** [space-concordia-robotics/robotics-networking#38]
The networking code uses Python's multiprocessing library to send messages over the network. We should do more research - are these messages sent with TCP or UDP? We should compare our requirements for the networking library to the expected performance and decide whether any changes are necessary.

**Comment by psyomn** [comment]
If you want help with this give me a shout.

**Comment by psyomn** [comment]
Come to think of it, we could correlate this to #2 such that we can have some hard metrics to compare against (ie stress test the networking code, generate the logs, and return them - did some commit improve performance or not?). Just spitballing ideas, it's safe to ignore me :P.

**Comment by msnidal** [comment]
Multiprocessing listeners use a TCP socket for internet connections like we're using (connection family type AF_INET in the docs)

https://docs.python.org/2/library/multiprocessing.html#multiprocessing.connection.Listener
