### ISSUE TITLE
Make simple UML diagrams of the system

### ISSUE THREAD

**Issue by psyomn** [space-concordia-robotics/robotics-networking#39]
This should help developers that are to join the project + the research students which want to give a shot at introducing self healing to the system.

@msnidal Help is appreciated, but I know you don't have much time (so don't feel bad if you can't make it). 

Going to start getting this out of the way tonight.

**Comment by psyomn** [comment]
(Modelio is a nice tool https://www.modelio.org/)

**Comment by Doomfest** [comment]
@psyomn  When do you think this will be done?

**Comment by psyomn** [comment]
Take a look at PR #40 

Proof read and merge.
