### ISSUE TITLE
testAttrSet is broken in test_client_validation.py

### ISSUE THREAD

**Issue by Doomfest** [space-concordia-robotics/robotics-networking#48]
The host and port test do not work. I commented them out for now until we can fix this. Build passes now. If you have a fix push to my "rawr" branch and then we can merge to master.  

@arevans3  @msnidal

**Comment by psyomn** [comment]
IIRC you just need to add attributes in the constructor

self.host = host

or something like that.

**Comment by Doomfest** [comment]
kk i think i fixed this. python was being stupid. We just need to test this branch int he lab and merge now.
