### ISSUE TITLE
Get Basic Client/Server interactions working

### ISSUE THREAD

**Issue by psyomn** [space-concordia-robotics/robotics-networking#5]
Need the foundations laid out for simple communications between a client and a
server. After we stub a few commands and test them out, we'll be able to iterate
through each one and add more functionality.

**Comment by Doomfest** [comment]
Shouldn't each child process update its state within it and then sends its state to the gateway?

**Comment by psyomn** [comment]
I'm thinking of just checking if services are up or not, nothing too crazy.

**Comment by Doomfest** [comment]
Yea that a simple way of doing it.
